### ISSUE TITLE
Error updating distance when running against bundler test suite

### ISSUE THREAD

**Issue by markburns** [ruby-analysis/delfos#27]
```
 ERROR -- : Whilst updating distance (eval)->lib/bundler/vendor/thor/lib/thor/base.rb
call_site_id: 3723
called_id: 3696 -
path_a: (eval) -> nil,
path_b: lib/bundler/vendor/thor/lib/thor/base.rb -> #<Pathname:lib/bundler/vendor/thor/lib/thor/base.rb>
[
"delfos/file_system/distance_calculation.rb:20:in `initialize'",
"delfos/file_system.rb:9:in `new'",
"delfos/file_system.rb:9:in `distance_calculation'",
"delfos/neo4j/distance/update.rb:50:in `handle'",
"delfos/neo4j/distance/update.rb:15:in `block in perform'",
"delfos/neo4j/distance/update.rb:14:in `each'",
"delfos/neo4j/distance/update.rb:14:in `perform'",
"delfos/neo4j.rb:33:in `update_distance!'",
"delfos.rb:47:in `finish!'",
]
```

Where
```
call_site
  file	(eval)
  line_number	2
called
  file	lib/bundler/vendor/thor/lib/thor/base.rb
  name	method_added
  line_number	583
  type	ClassMethod
```

**Comment by markburns** [comment]
Wasn't running the rake task for the specs in bundler, so this is probably irrelevant
